---
#- import_tasks: install.yml
#  tags:
#    - install
#
#- import_tasks: config.yml
#  tags:
#    - config

- import_tasks: config_ssl.yml
  tags:
    - config_ssl

#- import_tasks: service.yml
#  tags:
#    - service

