---
- import_tasks: install.yml
  tags:
    - install

- import_tasks: config.yml
  tags:
    - config

- import_tasks: config_ssl.yml
  tags:
    - config_ssl
  when: dovecot_ssl != "no"

- import_tasks: service.yml
  tags:
    - service

