---
- name: reload apache
  systemd:
    name: "{{ apache_service_name }}"
    state: reloaded

- name: restart apache
  systemd:
    name: "{{ apache_service_name }}"
    state: restarted
  when: apache_manage_service