---
- name: "Update nginx main configuration file"
  template:
    src: "nginx.conf.j2"
    dest: "{{ nginx_configuration_folder }}/nginx.conf"
    mode: 0644
    owner: root
    group: root
  notify: "restart nginx"