---
- name: "Upadate default configuration file for nginx"
  template:
    src: "default_vhost.conf.j2"
    dest: "{{ nginx_configuration_folder }}/sites-available/default.conf"
    mode: 0644
    owner: root
    group: root
  notify: "reload nginx"

- name: "Create the configurations for sites"
  template:
    src: "nginx_template.conf.j2"
    dest: "{{ nginx_configuration_folder }}/sites-available/{{ item }}.conf"
    mode: 0644
    owner: root
    group: root
  with_items: "{{ nginx_sites_to_deploy }}"
  notify:
    - reload nginx

- name: Create links for sites-enabled
  file:
    state: link
    src: "{{ nginx_configuration_folder }}/sites-available/{{ item }}.conf"
    dest: "{{ nginx_configuration_folder }}/sites-enabled/{{ item }}.conf"
  with_items:
    - default
    - "{{ nginx_sites_to_deploy }}"
  notify:
    - reload nginx


