---
- name: "Copy TLS key"
  template:
    src: "{{ nginx_certificates_folder }}{{ application_name }}/{{ application_name }}_nginx.key"
    dest: "/etc/nginx/ssl/{{ application_name }}_nginx.key"
    mode: 0644
    owner: root
    group: root
  notify: "restart nginx"

- name: "Copy TLS certificate"
  template:
    src: "{{ nginx_certificates_folder }}{{ application_name }}/{{ application_name }}_nginx.crt"
    dest: "/etc/nginx/ssl/{{ application_name }}_nginx.crt"
    mode: 0644
    owner: root
    group: root
  notify: "restart nginx"