---
- name: "nginx_application_vhost must be defined"
  assert:
    that:
      - nginx_application_vhost is defined

- import_tasks: install.yml

- import_tasks: config_nginx.yml

- import_tasks: config_ssl.yml
  when: nginx_use_letsencrypt == false

- import_tasks: config_letsencrypt.yml
  when: nginx_use_letsencrypt == true

- import_tasks: config_vhost.yml

- name: "Ensure nginx service is enabled and started"
  systemd:
    name: "nginx"
    state: started
    enabled: yes