---
- name: "nginx_application_vhost must be defined"
  assert:
    that:
      - nginx_application_vhost is defined

- import_tasks: install.yml

- import_tasks: config.yml

- name: "Ensure nginx service is enabled and startd"
  systemd:
    name: "nginx"
    state: started
    enabled: yes