---
- import_tasks: install.yml

- import_tasks: config.yml

- import_tasks: config_ssl.yml
  when: nginx_ssl

- name: "Ensure nginx service is enabled and startd"
  systemd:
    name: "nginx"
    state: started
    enabled: yes