---
- name: "Deploy SSL certificates"
  copy:
    src: "{{ config_bucket_dir }}/{{ item.src }}"
    dest: "/etc/ssl/certs/{{ item.dest }}"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ apache_certificates }}"

- name: "Deploy SSL private keys"
  copy:
    src: "{{ config_bucket_dir }}/{{ item.src }}"
    dest: "/etc/ssl/private/{{ item.dest }}"
    owner: root
    group: root
    mode: 0640
  with_items: "{{ apache_private_keys }}"