---
- name: "Custom configurations"
  template:
    src: custom.conf
    dest: "{{ apache_config_path }}/{{ apache_custom_configdir }}/custom.conf"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
    validate: "echo '%s' && apache2ctl configtest"
  notify: reload apache

- name: "Enable Security Configuration"
  file:
    src: "{{ apache_config_path }}/conf-available/custom.conf"
    dest: "{{ apache_config_path }}/conf-enabled/custom.conf"
    state: link
  when:
    - apache_custom_configdir == "conf-available"
  notify: reload apache

- name: "Drop default virtualhost"
  file:
    path: "{{ apache_config_path }}/sites-{{ item }}/000-default.conf"
    state: absent
  with_items:
    - enabled
    - available
  when: not apache_catchall_virtualhost
  notify: reload apache

- name: "Default vhost"
  template:
    src: default_virtualhost.conf
    dest: "{{ apache_config_path }}/sites-available/000-default.conf"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
    validate: "echo '%s' && apache2ctl configtest"
  when: apache_catchall_virtualhost
  notify: reload apache

- name: "Enable default vhost"
  file:
    src: "{{ apache_config_path }}/sites-available/000-default.conf"
    dest: "{{ apache_config_path }}/sites-enabled/000-default.conf"
    state: link
    validate: "echo '%s' && apache2ctl configtest"
  when: apache_catchall_virtualhost
  notify: reload apache

- name: "Localhost vhost"
  template:
    src: localhost_virtualhost.conf
    dest: "{{ apache_config_path }}/sites-available/localhost.conf"
    owner: root
    group: "{{ root_group }}"
    mode: 0644
    validate: "echo '%s' && apache2ctl configtest"
  when: apache_enable_localhost_virtualhost
  notify: reload apache

- name: "Enable localhost vhost"
  file:
    src: "{{ apache_config_path }}/sites-available/localhost.conf"
    dest: "{{ apache_config_path }}/sites-enabled/localhost.conf"
    state: link
    validate: "echo '%s' && apache2ctl configtest"
  when: apache_enable_localhost_virtualhost
  notify: reload apache
