---
- name: "Update apt cache"
  apt:
    update_cache: yes
    cache_valid_time: 3600
    force_apt_get: yes

- name: "Install package"
  apt:
    name: "{{ apache_package_name }}"
    state: present
    force_apt_get: yes
