---
- name: "mod_jk Installation"
  apt:
    name: "{{ apache_module_names.jk }}"
    state: present
  when: "item.state == 'present'"
  with_items: "{{ apache_modules | selectattr('name', 'match', '^jk$') | list }}"
  notify: restart apache

- name: "mod_jk Configuration"
  template:
    src: "mod_jk.conf"
    dest: "{{ apache_config_path }}/mods-available/jk.conf"
    owner: root
    group: "{{ root_group }}"
  when: "item.state == 'present'"
  with_items: "{{ apache_modules | selectattr('name', 'match', '^jk$') | list }}"
  notify: reload apache

- name: "mod_jk workers.properties"
  template:
    src: "workers.properties"
    dest: "{{ apache_config_path }}/workers.properties"
    owner: root
    group: "{{ root_group }}"
  when: "item.state == 'present'"
  with_items: "{{ apache_modules | selectattr('name', 'match', '^jk$') | list }}"
  notify: reload apache

- name: "enable mod_jk"
  apache2_module:
    name: jk
    state: "{{ item.state | default('absent') }}"
  with_items: "{{ apache_modules | selectattr('name', 'match', '^jk$') | list }}"
  notify: reload apache
