---
- name: "Manage mpm modules activation"
  apache2_module:
    name: "{{ item.name }}"
    state: "{{ item.state | default(absent) }}"
    ignore_configcheck: yes
  with_items: "{{ apache_modules | selectattr('name', 'match', '^mpm') | list | sort(attribute='state', reverse=True) }}"
  notify: restart apache

- name: "Manage modules activation"
  apache2_module:
    name: "{{ item.name }}"
    state: "{{ item.state | default(absent) }}"
  with_items: "{{ apache_modules | rejectattr('name', 'match', '^mpm') | list }}"
  notify: restart apache
