---
- name: "Manage mpm modules activation (absent)"
  apache2_module:
    name: "{{ item.name }}"
    state: "absent"
    ignore_configcheck: True
  with_items: "{{ apache_modules | selectattr('name', 'match', '^mpm') | list | sort(attribute='state', reverse=True) }}"
  when: item.state == "absent"
  notify: restart apache

- name: "Manage mpm modules activation (present)"
  apache2_module:
    name: "{{ item.name }}"
    state: "present"
    ignore_configcheck: True
  with_items: "{{ apache_modules | selectattr('name', 'match', '^mpm') | list | sort(attribute='state', reverse=True) }}"
  when: item.state == "present"
  notify: restart apache

- name: "Manage modules activation"
  apache2_module:
    name: "{{ item.name }}"
    state: "{{ item.state | default(absent) }}"
  with_items: "{{ apache_modules | rejectattr('name', 'match', '^mpm') | list }}"
  notify: restart apache

- name: "mpm_worker Configuration"
  template:
    src: "{{ item.name }}.conf.j2"
    dest: "{{ apache_config_path }}/mods-available/{{ item.name }}.conf"
    owner: root
    group: "{{ root_group }}"
  when: "item.state == 'present'"
  with_items: "{{ apache_modules | selectattr('name', 'match', '^mpm') | list }}"
  notify: reload apache