---
- hosts: "{{ filter }}:&dc_{{ dc }}:&cmp_mariadb:&app_email"
  become: true
  vars:
    mysql_script_db_name: "mailserver"
    mysql_script_script: "{{ role_path }}/../../inventory/group_vars/app_email/{{ mysql_script_db_name }}.sql.j2"
  roles:
    - { role: mysql_script, when: db_init is defined and db_init | bool }

# Include postfix
- include: ../system/postfix.yml
  vars:
    filter: "app_email"