---
#- hosts: "{{ filter }}:&dc_{{ dc }}:&cmp_nginx:&app_piwigo"
#  vars:
#    application_name: "piwigo"
#  become: true
#  roles:
#    - nginx

#- hosts: "{{ filter }}:&dc_{{ dc }}:&cmp_mariadb:&app_piwigo"
#  become: true
#  vars:
#    mysql_profile: "{{ mariadb_piwigo_profile }}"
#  roles:
#    - mysql

#- hosts: "{{ filter }}:&cmp_apache:&dc_{{ dc }}:&app_piwigo"
#  become: true
#  roles:
#    - apache


- hosts: "{{ filter }}:&cmp_apache:&dc_{{ dc }}:&app_piwigo"
  become: true
  roles:
    - apache_deploy

