---
# Create lets encrtypt certificates (DNS entry must be created first)
- import_playbook: ../system/letsencrypt.yml
  vars:
    letsencrypt_app: "webmail"
  when:
    - letsencrypt_create is defined
    - letsencrypt_create | bool

- hosts: "{{ filter }}:&dc_{{ dc }}:&cmp_nginx:&app_roundcube"
  vars:
    nginx_aliases:
      - "roundcube"
    nginx_application_vhost: "webmail"
    nginx_proxy_pass_host: "127.0.0.1"
    nginx_proxy_pass_port: "8081"
    nginx_use_letsencrypt: true
  become: true
  roles:
    - nginx

- hosts: "{{ filter }}:&dc_{{ dc }}:&cmp_mariadb:&app_roundcube"
  become: true
  vars:
    mysql_profile: "{{ mariadb_maindb_profile }}"
  roles:
    - mysql

- hosts: "{{ filter }}:&dc_{{ dc }}:&cmp_mariadb:&app_roundcube"
  become: true
  vars:
    mysql_script_db_name: "roundcube"
    mysql_script_script: "{{ role_path }}/../../inventory/group_vars/app_{{ mysql_script_db_name }}/roundcube.sql"
  roles:
    - { role: mysql_script, when: db_init is defined and db_init | bool }

- hosts: "{{ filter }}:&cmp_apache:&dc_{{ dc }}:&app_roundcube"
  become: true
  roles:
    - apache

- hosts: "{{ filter }}:&cmp_php:&dc_{{ dc }}:&app_roundcube"
  become: true
  vars:
    php_app: "roundcube"
    php_app_version: "1.4.0"
    php_version: "7.3"
    php_app_config_files:
      - { src: "config.inc.php.j2", dst: "config/config.inc.php" }
    php_app_extra_files: []
  roles:
    - php
