---
- name: "Add hostname to 127.0.1.1 in /etc/hosts"
  lineinfile:
    dest: "/etc/hosts"
    regexp: "^127.0.1.1"
    line: "127.0.1.1 vps528223.ovh.net vps528223 piwigo.{{ system_base_domain_name }} piwigo"
    insertafter: EOF

- name: "Create Group"
  piwigo_group:
    name: "{{ item }}"
    state: "present"
    url_username: "{{ piwigo_url_username }}"
    url_password: "{{ piwigo_url_password }}"
    url: "{{ piwigo_url }}"
  with_items: "{{ piwigo_group }}"

- name: "Create a list of user"
  piwigo_user:
    name: "{{ item.key }}"
    password: "{{ item.value.password }}"
    email: "{{ item.value.email }}"
    send_password_by_mail: false
    url_username: "{{ piwigo_url_username }}"
    url_password: "{{ piwigo_url_password }}"
    url: "{{ piwigo_url }}"
    state: "present"
  no_log: true
  with_dict: "{{ piwigo_user }}"

- name: "Create albums"
  piwigo_category:
    name: "{{ item.key }}"
    url_username: "{{ piwigo_url_username }}"
    url_password: "{{ piwigo_url_password }}"
    url: "{{ piwigo_url }}"
    state: "present"
    comment: "{{ item.value.comment }}"
    status: "{{ item.value.status }}"
  with_dict: "{{ piwigo_category }}"


# TODO : Remove install.php file

# TODO : Manage Plugins
