---
- name: "Deploy templates congiguration files"
  template:
    src: "{{ item }}.j2"
    dest: "{{ wordpress_webroot }}/config/{{ item }}"
    owner: www-data
    group: www-data
    mode: 0755
  with_items:
    - config.inc.php
