---
- name: "Create Apache wordpress folder"
  file:
    name: "/var/www/html/wordpress"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: "Install wordpress from {{ wordpress_download_url }} in version {{ wordpress_version }}"
  unarchive:
    src: "https://wordpress.org/latest.tar.gz"
    dest: "{{ wordpress_webroot }}/"
    remote_src: yes
    owner: www-data
    group: www-data
    mode: 0755
  notify: reload apache
