---
- name: "Create Apache wordpress folder"
  file:
    name: "/var/www/html/wordpress"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: "Install wordpress from {{ wordpress_download_url }} in version {{ wordpress_version }}"
  unarchive:
    src: "{{ wordpress_download_url }}/{{ wordpress_version }}/wordpressmail-{{ wordpress_version }}.zip"
    dest: "{{ wordpress_webroot }}/"
    remote_src: yes
    owner: www-data
    group: www-data
    mode: 0755
    extra_opts:
      - '--strip-components=1'
   notify: reload apache
