# tasks file for postfix
---
- name: "facts | "
  set_fact:
     is_docker_guest: "{{ ansible_virtualization_role | default('host') == 'guest' and ansible_virtualization_type | default('none') == 'docker' }}"
  tags:
    - configuration
    - postfix
    - postfix-facts

- name: "Configure debconf"
  debconf:
    name: "{{ item.name }}"
    question: "{{ item.question }}"
    value: "{{ item.value }}"
    vtype: "{{ item.vtype }}"
  with_items: "{{ postfix_debconf_selections }}"
  tags:
    - configuration
    - postfix
    - postfix-install

- name: "Install package"
  apt:
    name: "{{ postfix_install }}"
    state: "{{ apt_install_state | default('latest') }}"
    update_cache: true
    cache_valid_time: "{{ apt_update_cache_valid_time | default(3600) }}"
  tags:
    - configuration
    - postfix
    - postfix-install

- name: "Configure mailname"
  template:
    src: mailname.j2
    dest: /etc/mailname
    owner: root
    group: root
    mode: 0644
  notify: restart postfix
  tags:
    - configuration
    - postfix
    - postfix-mailname

- name: "Update configuration file"
  template:
    src: main.cf.j2
    dest: /etc/postfix/main.cf
    owner: root
    group: root
    mode: 0644
  notify: restart postfix
  tags:
    - configuration
    - postfix
    - postfix-configuration

- name: "Configure sasl username/password"
  template:
    src: sasl_passwd.j2
    dest: /etc/postfix/sasl_passwd
    owner: root
    group: root
    mode: 0600
  when: postfix_relayhost != false
  no_log: true
  notify:
    - postmap sasl_passwd
    - restart postfix
  tags:
    - configuration
    - postfix
    - postfix-sasl-passwd

- name: "Configure aliases"
  template:
    src: "aliases.j2"
    dest: "/etc/aliases"
    owner: "root"
    group: "root"
    mode: "0644"
  with_items: "{{ postfix_aliases }}"
  notify:
    - "new aliases"
  tags:
    - configuration
    - postfix
    - postfix-aliases

- name: "Configure sender canonical maps"
  lineinfile:
    dest: /etc/postfix/sender_canonical_maps
    regexp: '^{{ item.sender }}.*'
    line: '{{ item.sender }} {{ item.rewrite }}'
    owner: root
    group: root
    mode: 0644
    create: true
    state: present
  with_items: "{{ postfix_sender_canonical_maps }}"
  notify:
    - postmap sender_canonical_maps
    - restart postfix
  tags:
    - configuration
    - postfix
    - postfix-sender-canonical-maps

- name: "Configure generic table"
  lineinfile:
    dest: /etc/postfix/generic
    regexp: '^{{ item.pattern }}.*'
    line: '{{ item.pattern }} {{ item.result }}'
    owner: root
    group: root
    mode: 0644
    create: true
    state: present
  with_items: "{{ postfix_generic }}"
  notify:
    - postmap generic
    - restart postfix
  tags:
    - configuration
    - postfix
    - postfix-generic-table

- name: "Start and enable service"
  service:
    name: postfix
    state: "{{ service_default_state | default('started') }}"
    enabled: "{{ service_default_enabled | default(true) | bool }}"
  tags:
    - configuration
    - postfix
    - postfix-start-enable-service
