---
- apt:
    name: "postfix-mysql"
    state: present
    update_cache: true
    cache_valid_time: "3600"

- name: "Configure Postfix (mysql-virtual)"
  template:
    src: "{{ item }}.j2"
    dest: "/etc/postfix/{{ item }}"
    owner: root
    group: root
    mode: 0644
  with_items:
    - mysql-virtual-alias-maps.cf
    - mysql-virtual-mailbox-domains.cf
    - mysql-virtual-mailbox-maps.cf
  notify: restart postfix