---
- assert:
    that:
      - lr_obj.rotate_period is defined
      - lr_obj.rotate_period in ['daily', 'weekly', 'monthly']
      - lr_obj.rotate_number is defined
  tags:
    - logrotate

- name: Setup logrotate.d scripts
  template:
    src: logrotate.d.j2
    dest: "{{ logrotate_conf_dir }}{{ lr_name }}"
  tags:
    - logrotate
