---
dc_apache_listening_config:
  '*':
    - 8080
    - 8081
    - 8082

dc_apache_mpm: 'prefork'

dc_apache_vhosts:
  - name: "piwigo"
    custom_log_format: "realip"
    document_root: "/var/www/html/piwigo"
    ip: "*"
    keepalive: true
    port: "8080"
    server_name: "piwigo.bleschet.fr"
  - name: "roundcube"
    custom_log_format: "realip"
    document_root: "/var/www/html/roundcube"
    ip: "*"
    keepalive: true
    port: "8081"
    server_name: "roundcube.bleschet.fr"
    server_aliases:
      - "webmail.bleschet.fr"
#    document_root_fragment: '<IfModule dir_module>DirectoryIndex index.html index.php</IfModule>'
  - name: "mediawiki"
    custom_log_format: "realip"
    document_root: "/var/www/html/mediawiki"
    ip: "*"
    keepalive: true
    port: "8082"
    server_name: "mediawiki.bleschet.fr"
