---
- name: "Configure log folder"
  file:
    path: "{{ roundcube_log_folder }}"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: "Deploy templates congiguration files"
  template:
    src: "{{ item }}.j2"
    dest: "{{ roundcube_webroot }}/config/{{ item }}"
    owner: www-data
    group: www-data
    mode: 0755
  with_items:
    - config.inc.php

- name: "Delete the installer folder"
  file:
    path: "{{ roundcube_webroot }}/{{ item }}"
    state: absent
  with_items:
    - installer
    - logs
    - temp

