---
- name: "Deploy /etc/default/postgrey file"
  template:
    src: "default.j2"
    dest: "/etc/default/postgrey"
    mode: 0644
    owner: root
    group: root
  notify: "restart postgrey"

- name: "Deploy PostGrey configuration"
  template:
    src: "{{ item }}.j2"
    dest: "{{ postgrey_conf_folder }}/{{ item }}"
  with_items:
    - whitelist_clients
    - whitelist_recipients
  notify: "reload postgrey"