---
- name: "Create Apache roundcube folder"
  file:
    name: "/var/www/html/roundcube"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: "Create link between package installation folder and apache roundcube folder"
  file:
    src: "/var/www/html/roundcube"
    dest: "/var/lib/roundcube"
    state: link

- name: "Install roundcube prerequisites packages"
  apt:
    name:
      - dbconfig-common
      - php-net-smtp
      - php-net-socket
      - php-auth-sasl
      - php-mail-mime
      - php-net-sieve
    update_cache: true
    state: "present"

- name: "Install roundcube"
  apt:
    name:
      - roundcube-mysql
      - roundcube-core
    update_cache: true
    state: "present"

- name: "Correct link for the roundcube log"
  file:
    src: "/var/log/roundcube"
    dest: "/var/www/html/roundcube/logs"
    state: link
