---
- name: "Create Apache roundcube folder"
  file:
    name: "/var/www/html/roundcube"
    state: directory
    owner: www-data
    group: www-data
    mode: 0755

- name: "Install roundcube prerequisites packages"
  apt:
    name:
      - php-net-smtp
      - php-net-socket
      - php-auth-sasl
      - php-mail-mime
      - php-net-sieve
      - php-net-idna2
    update_cache: true
    state: "present"

- name: "Install roundcube"
  unarchive:
    src: "{{ roundcube_download_url }}/{{ roundcube_version }}/roundcubemail-{{ roundcube_version }}.tar.gz"
    dest: "{{ roundcube_webroot }}/"
    remote_src: yes
    owner: www-data
    group: www-data
    mode: 0755
    extra_opts:
      - '--strip-components=1'
#  notify: restart apache

- name: "Install js scripts"
  command: "{{ roundcube_webroot }}/bin/install-jsdeps.sh"
  become_user: www-data
