---
dc_apache_listening_config:
  '127.0.0.1':
    - 8080
    - 8081
    - 8082

dc_apache_mpm: 'prefork'

dc_apache_vhosts:
  - name: "piwigo"
    custom_log_format: "realip"
    document_root: "/var/www/html/piwigo"
    ip: "127.0.0.1"
    keepalive: true
    port: "8080"
    server_name: "piwigo.bleschet.fr"
  - name: "roundcube"
    custom_log_format: "realip"
    document_root: "/var/www/html/roundcube"
    ip: "127.0.0.1"
    keepalive: true
    port: "8081"
    server_name: "roundcube.bleschet.fr"
    server_aliases:
      - "webmail.bleschet.fr"
#    document_root_fragment: '<IfModule dir_module>DirectoryIndex index.html index.php</IfModule>'
  - name: "mediawiki"
    custom_log_format: "realip"
    document_root: "/var/www/html/mediawiki"
    ip: "127.0.0.1"
    keepalive: true
    port: "8082"
    server_name: "mediawiki.bleschet.fr"


## PHP Settings
#apache_mod_php_enable: yes
#
#app_php_version: 7.0
#app_php_extra_modules:
#  - 'php{{ app_php_version }}-mysql'
#  - 'php{{ app_php_version }}-curl'
#  - 'php{{ app_php_version }}-gd'
#  - 'php{{ app_php_version }}-gmp'
#  - 'php{{ app_php_version }}-imagick'
#  - 'php{{ app_php_version }}-intl'
#  - 'php{{ app_php_version }}-mcrypt'
#  - 'php{{ app_php_version }}-xsl'


#apache_src_url:  "http://piwigo.org/download/dlcounter.php?code=latest"
#
#apache_php_files:
#  config_templates:
#    - { src: "database.inc.php", dst: "local/config/database.inc.php" }