---
# ==============================================
#   Load a SQL Script into a MySQL Database
# ==============================================
# Requires the following arguments :
#   - sql_script : path of the SQL script to run
#   - db_name : name of the database to load data into
#   - any other argument used in the sql script template.


- name: "Transfer SQL Script"
  template:
    src: '{{ mysql_script_script }}'
    dest: "/tmp/{{ ansible_date_time.date }}_sql_script.sql"
    mode: 0644
  register: script_transfer

- name: "Load Database"
  shell: mysql -v {{ mysql_script_db_name }} < /tmp/{{ ansible_date_time.date }}_sql_script.sql
  when:
    - script_transfer.failed == false
    - script_transfer.size != 0

- name: "Remove SQL statements"
  file:
    path: "/tmp/{{ ansible_date_time.date }}_sql_script.sql"
    state: absent
