---
- name: Create MySQL configuration directory
  file:
    path: "{{ mysql_config_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy my.cnf global MySQL configuration.
  template:
    src: my.cnf.j2
    dest: "{{ mysql_config_file }}"
    owner: root
    group: root
    mode: 0644
    force: "{{ overwrite_global_mycnf }}"
  notify: restart mysql

- name: Verify mysql include directory exists.
  file:
    path: "{{ mysql_config_include_dir }}"
    state: directory
    owner: root
    group: root
    mode: 0755
  when: mysql_config_include_files | length

- name: Copy my.cnf override files into include directory.
  template:
    src: "{{ item.src }}"
    dest: "{{ mysql_config_include_dir }}/{{ item.src | basename }}"
    owner: root
    group: root
    mode: 0644
    force: "{{ item.force | default(False) }}"
  with_items: "{{ mysql_config_include_files }}"
  notify: restart mysql

- name: "Create logdir"
  file:
    path: "{{ mysql_log_dir }}"
    state: directory
    owner: "mysql"
    group: "mysql"

- name: "Create slow query log file (if configured)"
  file:
    path: "{{ mysql_slow_query_log_file }}"
    state: touch
    owner: "mysql"
    group: "mysql"
  when: mysql_slow_query_log_enabled

- name: "Create datadir if it does not exist"
  file:
    path: "{{ mysql_datadir }}"
    state: directory
    owner: mysql
    group: mysql
    mode:  0755
    setype: mysqld_db_t
  register: mysql_datadir_created

- name: "Create tmpdir if it does not exist"
  file:
    path: "{{ mysql_tmpdir }}"
    state: directory
    owner: mysql
    group: mysql
    mode: 0755
  when: mysql_tmpdir != "/tmp"

- name: "Create initial database if datadir was created"
  command: "mysql_install_db --datadir={{ mysql_datadir }}"
  become: true
  become_user: mysql
  when: mysql_datadir_created is changed

- name: "Drop current started service due to mysql_install_db"
  service:
    name: "{{ mysql_daemon }}"
    state: stopped
  when: mysql_datadir_created is changed

- name: Create error log file (if configured).
  shell: "touch {{ mysql_log_error }} creates={{ mysql_log_error }}"
  when: mysql_log == "" and mysql_log_error != ""

- name: Set ownership on error log file (if configured).
  file:
    path: "{{ mysql_log_error }}"
    state: file
    owner: mysql
    group: mysql
    mode: 0640
  when: mysql_log == "" and mysql_log_error != ""

- name: Ensure MySQL is started and enabled on boot.
  service:
    name: "{{ mysql_daemon }}"
    state: started
    enabled: "{{ mysql_enabled_on_startup }}"
  register: mysql_service_configuration
