---
- name: Ensure MySQL databases are present.
  mysql_db:
    name: "{{ item.name }}"
    login_unix_socket: "{{ mysql_socket }}"
    collation: "{{ item.collation | default('utf8_general_ci') }}"
    encoding: "{{ item.encoding | default('utf8') }}"
    state: present
  with_items: "{{ mysql_databases }}"
