---
# This role part has just the goal to override role vars with instance vars
# Yes you eyes will be hurt by this
# No i'm not sorry :D

- name: "Override default configurations with instance configuration"
  set_fact:
    mysql_daemon: "mysql@{{ instance_name }}"
    mysql_config_dir: "/etc/mysql_{{ instance_name }}"
    mysql_socket: "/var/run/mysqld_{{ instance_name }}/mysqld.sock"
    mysql_root_username: "{{ instance_vars.root_username | default(mysql_root_username) }}"
    mysql_root_password: "{{ instance_vars.root_password | default(mysql_root_password) }}"
    mysql_root_password_update: "{{ instance_vars.root_password_update | default(mysql_root_password_update) }}"
    # my.cnf related variables
    mysql_port: "{{ instance_vars.port | default(mysql_port) }}"
    mysql_bind_address: "{{ instance_vars.bind_address | default(mysql_bind_address) }}"
    mysql_datadir: "{{ mysql_root_datadir }}/{{ instance_name }}"
    mysql_pid_file: "/var/run/mysqld_{{ instance_name }}/mysqld.pid"
    mysql_skip_name_resolve: "{{ instance_vars.skip_name_resolve | default(mysql_skip_name_resolve) }}"
    mysql_tmpdir: "{{ mysql_root_tmpdir }}/{{ instance_name }}"
    mysql_slow_query_log_enabled: "{{ instance_vars.slow_query_log_enabled | default(mysql_slow_query_log_enabled) }}"
    mysql_log_dir: "/var/log/mysql_{{ instance_name }}"
    mysql_slow_query_log_file: "/var/log/mysql_{{ instance_name }}/mysql_slow_query.log"
    mysql_slow_query_time: "{{ instance_vars.slow_query_time | default(mysql_slow_query_time) }}"
    mysql_log_slow_verbosity: "{{ instance_vars.log_slow_verbosity | default(mysql_log_slow_verbosity) }}"
    mysql_concurrent_insert: "{{ instance_vars.concurrent_insert | default(mysql_concurrent_insert) }}"
    mysql_key_buffer_size: "{{ instance_vars.key_buffer_size | default(mysql_key_buffer_size) }}"
    mysql_key_cache_segments: "{{ instance_vars.key_cache_segments | default(mysql_key_cache_segments) }}"
    mysql_max_allowed_packet: "{{ instance_vars.max_allowed_packet | default(mysql_max_allowed_packet) }}"
    mysql_net_buffer_length:  "{{ instance_vars.net_buffer_length | default(mysql_net_buffer_length) }}"
    mysql_table_open_cache: "{{ instance_vars.table_open_cache | default(mysql_table_open_cache) }}"
    mysql_table_definition_cache: "{{ instance_vars.table_definition_cache | default(mysql_table_definition_cache) }}"
    mysql_sort_buffer_size: "{{ instance_vars.sort_buffer_size | default(mysql_sort_buffer_size) }}"
    mysql_read_buffer_size: "{{ instance_vars.read_buffer_size | default(mysql_read_buffer_size) }}"
    mysql_read_rnd_buffer_size: "{{ instance_vars.read_rnd_buffer_size | default(mysql_read_rnd_buffer_size) }}"
    mysql_myisam_sort_buffer_size: "{{ instance_vars.myisam_sort_buffer_size | default(mysql_myisam_sort_buffer_size) }}"
    mysql_thread_cache_size: "{{ instance_vars.thread_cache_size | default(mysql_thread_cache_size) }}"
    mysql_query_cache_size: "{{ instance_vars.query_cache_size | default(mysql_query_cache_size) }}"
    mysql_query_cache_type: "{{ instance_vars.query_cache_type | default(mysql_query_cache_type) }}"
    mysql_query_cache_limit: "{{ instance_vars.query_cache_limit | default(mysql_query_cache_limit) }}"
    mysql_max_connections: "{{ instance_vars.max_connections | default(mysql_max_connections) }}"
    mysql_open_files_limit: "{{ instance_vars.open_files_limit | default(mysql_open_files_limit) }}"
    mysql_tmp_table_size: "{{ instance_vars.tmp_table_size | default(mysql_tmp_table_size) }}"
    mysql_max_heap_table_size: "{{ instance_vars.max_heap_table_size | default(mysql_max_heap_table_size) }}"
    mysql_join_buffer_size: "{{ instance_vars.join_buffer_size | default(mysql_join_buffer_size) }}"
    mysql_join_buffer_space_limit: "{{ instance_vars.join_buffer_space_limit | default(mysql_join_buffer_space_limit) }}"
    mysql_lower_case_table_names: "{{ instance_vars.lower_case_table_names | default(mysql_lower_case_table_names) }}"
    mysql_wait_timeout: "{{ instance_vars.wait_timeout | default(mysql_wait_timeout) }}"
    mysql_connect_timeout: "{{ instance_vars.connect_timeout | default(mysql_connect_timeout) }}"
    mysql_interactive_timeout: "{{ instance_vars.interactive_timeout | default(mysql_interactive_timeout) }}"
    mysql_performance_schema: "{{ instance_vars.performance_schema | default(mysql_performance_schema) }}"
    mysql_thread_pool_size: "{{ instance_vars.thread_pool_size | default(mysql_thread_pool_size) }}"
    mysql_innodb_file_per_table: "{{ instance_vars.innodb_file_per_table | default(mysql_innodb_file_per_table) }}"
    mysql_innodb_buffer_pool_size: "{{ instance_vars.innodb_buffer_pool_size | default(mysql_innodb_buffer_pool_size) }}"
    mysql_innodb_log_file_size: "{{ instance_vars.innodb_log_file_size | default(mysql_innodb_log_file_size) }}"
    mysql_innodb_log_buffer_size: "{{ instance_vars.innodb_log_buffer_size | default(mysql_innodb_log_buffer_size) }}"
    mysql_innodb_flush_log_at_trx_commit: "{{ instance_vars.innodb_flush_log_at_trx_commit | default(mysql_innodb_flush_log_at_trx_commit) }}"
    mysql_innodb_lock_wait_timeout: "{{ instance_vars.innodb_lock_wait_timeout | default(mysql_innodb_lock_wait_timeout) }}"
    mysql_innodb_thread_concurrency: "{{ instance_vars.innodb_thread_concurrency | default(mysql_innodb_thread_concurrency) }}"
    mysql_innodb_flush_method: "{{ instance_vars.innodb_flush_method | default(mysql_innodb_flush_method) }}"
    mysql_innodb_thread_sleep_delay: "{{ instance_vars.innodb_thread_sleep_delay | default(mysql_innodb_thread_sleep_delay) }}"
    mysql_innodb_large_prefix: "{{ instance_vars.innodb_large_prefix | default(mysql_innodb_large_prefix) }}"
    mysql_innodb_file_format: "{{ instance_vars.innodb_file_format | default(mysql_innodb_file_format) }}"
    mysql_mysqldump_max_allowed_packet: "{{ instance_vars.mysqldump_max_allowed_packet | default(mysql_mysqldump_max_allowed_packet) }}"
    mysql_log: "{{ instance_vars.log | default(mysql_log) }}"
    mysql_log_error: "/var/log/mysql_{{ instance_name }}/mysql.err"
    mysql_config_include_files: "{{ instance_vars.config_include_files | default(mysql_config_include_files) }}"
    mysql_databases: "{{ instance_vars.databases | default(mysql_databases) }}"
    mysql_users: "{{ instance_vars.users | default(mysql_users) }}"
    mysql_server_id: "{{ instance_vars.server_id | default(mysql_server_id) }}"
    mysql_max_binlog_size: "{{ instance_vars.max_binlog_size | default(mysql_max_binlog_size) }}"
    mysql_binlog_format: "{{ instance_vars.binlog_format | default(mysql_binlog_format) }}"
    mysql_expire_logs_days: "{{ instance_vars.expire_logs_days | default(mysql_expire_logs_days) }}"
    mysql_log_warnings: "{{ instance_vars.log_warnings | default(mysql_log_warnings) }}"
    mysql_replication_role: "{{ instance_vars.replication_role | default(mysql_replication_role) }}"
    mysql_replication_master: "{{ instance_vars.replication_master | default(mysql_replication_master) }}"
    mysql_replication_user: "{{ instance_vars.replication_user | default(mysql_replication_user) }}"
    
- include_tasks: instance.yml