---
apache_roundcube:
  rouncube_version: "1.3.8"
  src_url: "https://github.com/roundcube/roundcubemail/releases/download/1.3.8/roundcubemail-1.3.8.tar.gz"
  apache_php_files:
    config_templates: []