---
# PHP Prequisite for roundcube
app_php_roundcube_extra_modules:
  - php-net-smtp
  - php-net-socket
  - php-auth-sasl
  - php-mail-mime
  - php-net-sieve
  - php-net-idna2

# Rpoundube Configuration
app_php_roundcube_cleanup_files_or_folder:
  - installer
  - logs
  - temp
app_php_roundcube_des_key: "[IzK5xoZv1dJyjseVx9fVv72"
app_php_roundcube_download_url: https://github.com/roundcube/roundcubemail/releases/download/{{ php_app_version }}/roundcubemail-{{ php_app_version }}.tar.gz
app_php_roundcube_extra_scripts:
  - "bin/install-jsdeps.sh"
app_php_roundcube_imap: 'ssl://mail.bleschet.fr'
app_php_roundcube_smtp_port: 587
