# defaults file for postfix
---
postfix_aliases:
  "postmaster": "root"

postfix_disable_vrfy_command: false
postfix_cafile:
postfix_certificate_request: "/etc/postfix/tls/domaine-cert.pem"
postfix_conf_submission: false
postfix_domain: "{{ ansible_domain }}"
postfix_dovecot_mysql_host: '127.0.0.1'
postfix_dovecot_mysql_db_name: 'servermail'
postfix_dovecot_mysql_user: 'usermail'
postfix_generic: []
postfix_install:
  - postfix
  - mailutils
  - libsasl2-2
  - sasl2-bin
  - libsasl2-modules
postfix_hostname: "{{ ansible_fqdn }}"
postfix_inet_interfaces: all
postfix_inet_protocols: all
postfix_mailbox_size_limit: 0
postfix_mailname: "{{ ansible_fqdn }}"
postfix_message_size_limit: 10240000
postfix_mydestination:
  - "{{ postfix_hostname }}"
  - localdomain
  - localhost
  - localhost.localdomain
postfix_mynetworks:
  - 127.0.0.0/8
  - '[::ffff:127.0.0.0]/104'
  - '[::1]/128'
postfix_mysql_alias_query: 'SELECT destination FROM virtual_aliases WHERE source=''%s'';'
postfix_mysql_domains_query: 'SELECT 1 FROM virtual_domains WHERE name=''%s'';'
postfix_mysql_users_query: 'SELECT 1 FROM virtual_users WHERE email=''%s'';'
posftix_mysql_virtual: false
postfix_opendkim: false
postfix_opendkim_socket: "local:var/run/opendkim/opendkim.sock"
postfix_private_key: "/etc/postfix/tls/domaine-key.pem"
postfix_relayhost: false
postfix_relayhost_port: 587
postfix_relaytls: false
postfix_sasl_auth_enable: true
postfix_sasl_user: "postmaster@{{ ansible_domain }}"
postfix_sasl_password: 'k8+haga4@#pR'
postfix_sasl_security_options: noanonymous
postfix_sasl_mechanism_filter: ''
postfix_sender_canonical_maps: []
postfix_smtpd_banner: '$myhostname ESMTP $mail_name (Ubuntu)'
postfix_smtpd_client_restrictions:
  - reject_unauth_pipelining
postfix_smtpd_helo_restrictions:
postfix_smtpd_relay_restrictions:
  - permit_mynetworks
  - permit_sasl_authenticated
  - defer_unauth_destination
postfix_smtpd_recipient_restrictions:
postfix_smtpd_sender_restrictions:
  - reject_unknown_sender_domain
  - reject_non_fqdn_sender
postfix_tls_enable: false
postfix_virtual_aliases: []
postfix_virtual_transport:
