---
dovecot_auth: "system"
dovecot_auth_debug: "no"
dovecot_auth_mechanisms:
  - "plain"
  - "login"
dovecot_auth_verbose: "yes"
dovecot_base_dir: "/var/run/dovecot"
dovecot_disable_plaintext_auth: "yes"
dovecot_doveadm_socket_path: "doveadm-server"
dovecot_doveadm_worker_count: 0
dovecot_force_imaps: True
dovecot_force_pop3s: True
dovecot_hierarchy_separator: "/"
dovecot_import_environment: "TZ"
dovecot_instance_name: "dovecot"
dovecot_listen:
  - "*"
  - "::"
dovecot_log_timestamp: "%Y-%m-%d %H:%M:%S "
dovecot_login_greeting: "Greetings to the mail server"
dovecot_mail_access_groups: "mail"
dovecot_mail_location: "mbox:~/mail:INBOX=/var/mail/%u"
dovecot_mailbox_location: "{{ dovecot_mailbox_location_base }}/%u"
dovecot_mailbox_location_base: "/var/mail"
dovecot_mail_privileged_group: "mail"
dovecot_postfix_smtp_auth: false
dovecot_protocols:
  - "lmtp"
  - "imap"
dovecot_shutdown_clients: "yes"
dovecot_ssl: "required"
dovecot_verbose_proctitle: "yes"
dovecot_vmail_group: "vmail"
dovecot_vmail_user: "vmail"
