---
# Prerequisite for template files
- name: "Set fact for config_bucket_dir, vhosts, apache_custom_configdir"
  set_fact:
    inventory_dir: "{{ role_path }}/../../inventory/group_vars"

- name: "Deploy template configs"
  template:
    src: "{{ inventory_dir }}/app_{{ php_app }}/{{ item.src }}"
    dest: "{{ php_app_webroot }}/{{ php_app }}/{{ item.dst }}"
    owner: www-data
    group: www-data
    mode: 0440
  with_items: "{{ php_app_config_files }}"

- name: "Deploy extra files"
  copy:
    src: "{{ inventory_dir }}/app_{{ php_app }}/{{ item.src }}"
    dest: "{{ php_app_webroot }}/{{ php_app }}/{{ item.dst }}"
    owner: www-data
    group: www-data
    mode: 0644
  with_items: "{{ php_app_extra_files }}"

#- name: "Deploy application extensions"
#  with_items: "{{ php_app_extensions }}"