---
# Prerequisite for template files
- name: "Set fact for config_bucket_dir, vhosts, apache_custom_configdir"
  set_fact:
    inventory_dir: "{{ role_path }}/../../inventory/group_vars"

- name: "Configure log folder"
  file:
    path: "{{ php_app_log_folder }}"
    state: directory
    owner: "{{ php_apache_user }}"
    group: "{{ php_apache_group }}"
    mode: 0755

- name: "Deploy template configs"
  template:
    src: "{{ inventory_dir }}/app_{{ php_app }}/{{ item.src }}"
    dest: "{{ php_app_webroot }}/{{ php_app }}/{{ item.dst }}"
    owner: "{{ php_apache_user }}"
    group: "{{ php_apache_group }}"
    mode: 0755
  loop: "{{ php_app_config_files }}"

- name: "Deploy extra files"
  copy:
    src: "{{ inventory_dir }}/app_{{ php_app }}/{{ item.src }}"
    dest: "{{ php_app_webroot }}/{{ php_app }}/{{ item.dst }}"
    owner: "{{ php_apache_user }}"
    group: "{{ php_apache_group }}"
    mode: 0644
  loop: "{{ php_app_extra_files }}"

- name: "Executes extra scripts"
  command: "{{ php_app_webroot }}/{{ php_app }}/bin/install-jsdeps.sh"
  become_user: www-data
  loop: "{{ lookup('vars', 'app_php_' + php_app  + '_extra_scripts') }}"

- name: "Delete the installer folder"
  file:
    path: "{{ php_app_webroot }}/{{ php_app }}/{{ item }}"
    state: absent
  loop: "{{ lookup('vars', 'app_php_' + php_app  + '_cleanup_files_or_folder') }}"

#- name: "Deploy application extensions"
#  with_items: "{{ php_app_extensions }}"