---
- name: "Install PHP packages"
  apt:
    name: "php{{ php_version }}"
    force_apt_get: yes
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: "Install extra packages"
  apt:
    name: "{{ lookup('vars', 'app_php_' + php_app  + '_extra_modules') }}"
    force_apt_get: yes
    state: present

