---
- name: "Install PHP packages"
  apt:
    name: "php{{ php_version }}"
    force_apt_get: yes
    state: present
    update_cache: yes
    cache_valid_time: 3600

- name: "Install PHP packages"
  apt:
    name:  "{{ php_modules }}"
    force_apt_get: yes
    state: present
