---
- name: "Creates lets encrypt config folder ({{ letsencrypt_config_folder }})"
  file:
    name: "{{ letsencrypt_config_folder }}"
    state: "directory"
    owner: "root"
    group: "root"
    mode: 0755
  tags:
    - config

- name: "Deploy letsencrypt configuration file for domain to manage"
  template:
    src: "domain.j2"
    dest: "{{ letsencrypt_config_folder }}/{{ letsencrypt_domains }}.conf"
    owner: root
    group: root
    mode: 0644
  tags:
    - config
