---
php_apache_service_name: "apache2"
php_base_installation_folder: "/etc/php/{{ php_version }}/apache2"
php_conf_extenstion_folder: /etc/php/{{ php_version }}/mods-available
php_app_config_files: []
php_app_extensions: []
php_app_extra_files: []

# Default PHP version to install on Debian-based OSes.
php_version: "7.0"


# OpCache settings.
php_opcache_zend_extension: "opcache.so"
php_opcache_enable: "1"
php_opcache_enable_cli: "0"
php_opcache_memory_consumption: "96"
php_opcache_interned_strings_buffer: "16"
php_opcache_max_accelerated_files: "4096"
php_opcache_max_wasted_percentage: "5"
php_opcache_validate_timestamps: "1"
php_opcache_revalidate_path: "0"
php_opcache_revalidate_freq: "2"
php_opcache_max_file_size: "0"
php_opcache_blacklist_filename: ""

# APCu settings.
php_enable_apc: true
php_apc_shm_size: "96M"
php_apc_enable_cli: "0"

php_expose_php: "On"
php_memory_limit: "256M"
php_max_execution_time: "60"
php_max_input_time: "60"
php_max_input_vars: "1000"
php_realpath_cache_size: "32K"

php_file_uploads: "On"
php_upload_max_filesize: "20M"
php_max_file_uploads: "20"
php_open_basedir:
  - "/var/www"
php_sql_safe_mode: "Off"

php_post_max_size: "32M"
php_date_timezone: "Europe/Paris"
php_allow_url_fopen: "On"
php_allow_url_include: "Off"

php_sendmail_path: "/usr/sbin/sendmail -t -i"
php_output_buffering: "4096"
php_short_open_tag: "Off"
php_disable_functions: []

php_session_cookie_lifetime: 0
php_session_gc_probability: 1
php_session_gc_divisor: 1000
php_session_gc_maxlifetime: 1440
php_session_save_handler: files
php_session_save_path: ''

php_error_reporting: "E_ALL & ~E_DEPRECATED & ~E_STRICT"
php_display_errors: "Off"
php_display_startup_errors: "Off"

# Applications
php_app: ""
php_app_download_url: ""
php_app_version: ""
php_app_webroot: "/var/www/html"
