---
letsencrypt_domains:
  -  piwigo.bleschet.fr
letsencrypt_key_size: 4096
letsencrypt_ca_url: "https://acme-v02.api.letsencrypt.org/directory"
lets_encrypt_mail_address: "cedric@bleschet.fr"
lets_encrypt_text: "True"
lets_encrypt_authenticator: "webroot"
lets_encrypt_webroot_path: "/usr/share/nginx/html"
lets_encrypt_agree_tos: True
lets_encrypt_config_folder: "/etc/letsencrypt/configs"