---
nginx_application_vhost: "default"
nginx_cert_file: "{{ dc_nginx_cert_file }}"
nginx_configuration_folder: "/etc/nginx"
nginx_key_file: "{{ dc_nginx_key_file }}"
nginx_server_name: "{{ nginx_application_vhost }}.{{ dc_domain_name }}"
nginx_sites_to_deploy:
  - "{{ nginx_application_vhost }}"