---
dovecot_auth: "sql"
dovecot_auth_debug: "no"
dovecot_auth_mechanisms:
  - "plain"
  - "login"
dovecot_auth_verbose: "yes"
dovecot_base_dir: "/var/run/dovecot"
dovecot_certificate_request: "{{ mailserver_certificate_request }}"
dovecot_disable_plaintext_auth: "yes"
dovecot_doveadm_socket_path: "doveadm-server"
dovecot_doveadm_worker_count: 0
dovecot_force_imaps: True
dovecot_force_pop3s: True
dovecot_hierarchy_separator: "/"
dovecot_import_environment: "TZ"
dovecot_instance_name: "dovecot"
dovecot_listen:
  - "*"
  - "::"
dovecot_log_timestamp: "%Y-%m-%d %H:%M:%S "
dovecot_login_greeting: "Greetings to the mail server"
dovecot_mail_access_groups: "mail"
dovecot_mail_location: "maildir:{{ dovecot_mailbox_location }}/Maildir"
dovecot_mailbox_location: "{{ dovecot_mailbox_location_base }}/%d/%n"
dovecot_mailbox_location_base: "/srv/mailboxes"
dovecot_mail_privileged_group: "mail"
dovecot_mariadb_password_query: 'SELECT email as user, password FROM virtual_users WHERE email=''%u'';'
dovecot_parameters_regenerate: 0
dovecot_postfix_smtp_auth: true
dovecot_private_key: "{{ mailserver_private_key }}"
dovecot_protocols:
  - "lmtp"
  - "imap"
dovecot_shutdown_clients: "yes"
dovecot_ssl: "required"
dovecot_ssl_cipher_list: "ALL:!LOW"
dovecot_verbose_proctitle: "yes"
dovecot_vmail_group: "vmail"
dovecot_vmail_user: "vmail"