---
# Configuration de l'application PHP
php_app: "{{ app_php_app }}"
php_app_config_files:  "{{ app_php_app_config_files | default([]) }}"
php_app_download_url: "{{ app_php_app_download_url  }}"
php_app_extra_files:  "{{ app_php_app_extra_files | default([]) }}"
php_app_version: "{{ app_php_version }}"
php_app_webroot: "/var/www/html"
php_app_versions_file: "/root/versions.txt"

# Configuration PHP
php_disable_functions: [ "pcntl_alarm", "pcntl_fork", "pcntl_waitpid", "pcntl_wait", "pcntl_wifexited", "pcntl_wifstopped",
"pcntl_wifsignaled", "pcntl_wifcontinued", "pcntl_wexitstatus", "pcntl_wtermsig", "pcntl_wstopsig", "pcntl_signal",
"pcntl_signal_dispatch", "pcntl_get_last_error", "pcntl_strerror", "pcntl_sigprocmask", "pcntl_sigwaitinfo",
"pcntl_sigtimedwait", "pcntl_exec", "pcntl_getpriority", "pcntl_setpriority", "exec", "passthru", "shell_exec", "system",
"proc_open", "popen", "curl_exec", "curl_multi_exec", "parse_ini_file", "show_source" ]

php_expose_php: "Off"
php_extra_modules: []
php_log_folder: "/var/log/apache2/{{ php_app | default('') }}"
php_modules: "{{ php_extra_modules + (app_php_extra_modules | default([])) }}"
php_open_basedir:
  - "{{ php_app_webroot }}"
  - "{{ php_tmp_folder }}"
  - "/usr/share/php" # PEAR module
  - "/var/log/apache2"
php_tmp_folder: "/tmp"

